[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32L433RC with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32L433RC"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
#DEFMT_RTT_BUFFER_SIZE = "2048"
